#!/bin/bash

# Image Analysis Preparation Script (Section-Based Approach)
# This script lists all screenshots organized by section for analysis

echo "=== Responsive Screenshots Analysis Preparation (Section-Based) ==="
echo ""
echo "Base directory: /root/projects/ai-automation-ru-final/responsive-screenshots/"
echo ""

echo "=== Analysis Sequence by Website Section ==="
echo ""

echo "Phase 1: Header/Navigation Section"
echo "----------------------------------"
echo "Files to analyze:"
echo "  - responsive-screenshots/macbook-pro-16-inch/header.png"
echo "  - responsive-screenshots/macbook-air-13-inch/header.png"
echo "  - responsive-screenshots/ipad-pro-(tablet)/header.png"
echo "  - responsive-screenshots/iphone-14-pro-(mobile)/header.png"
echo "  - responsive-screenshots/iphone-se-(small-mobile)/header.png"
echo ""

echo "Phase 2: Timeline Cards Section"
echo "------------------------------"
echo "Files to analyze:"
echo "  - responsive-screenshots/macbook-pro-16-inch/timeline-cards.png"
echo "  - responsive-screenshots/macbook-air-13-inch/timeline-cards.png"
echo "  - responsive-screenshots/ipad-pro-(tablet)/timeline-cards.png"
echo "  - responsive-screenshots/iphone-14-pro-(mobile)/timeline-cards.png"
echo "  - responsive-screenshots/iphone-se-(small-mobile)/timeline-cards.png"
echo ""

echo "Phase 3: Stats Cards Section"
echo "---------------------------"
echo "Files to analyze:"
echo "  - responsive-screenshots/macbook-pro-16-inch/stats-cards.png"
echo "  - responsive-screenshots/macbook-air-13-inch/stats-cards.png"
echo "  - responsive-screenshots/ipad-pro-(tablet)/stats-cards.png"
echo "  - responsive-screenshots/iphone-14-pro-(mobile)/stats-cards.png"
echo "  - responsive-screenshots/iphone-se-(small-mobile)/stats-cards.png"
echo ""

echo "Phase 4: Pricing Cards Section"
echo "-----------------------------"
echo "Files to analyze:"
echo "  - responsive-screenshots/macbook-pro-16-inch/pricing-cards.png"
echo "  - responsive-screenshots/macbook-air-13-inch/pricing-cards.png"
echo "Note: May be missing on tablet and mobile devices - check full-page.png"
echo ""

echo "Phase 5: Full Page Layout and Flow"
echo "----------------------------------"
echo "Files to analyze:"
echo "  - responsive-screenshots/macbook-pro-16-inch/full-page.png"
echo "  - responsive-screenshots/macbook-air-13-inch/full-page.png"
echo "  - responsive-screenshots/ipad-pro-(tablet)/full-page.png"
echo "  - responsive-screenshots/iphone-14-pro-(mobile)/full-page.png"
echo "  - responsive-screenshots/iphone-se-(small-mobile)/full-page.png"
echo ""

echo "=== Cross-Cutting Analysis Phases ==="
echo ""
echo "Phase 6: Typography and Readability"
echo "Analyze text across all sections and devices:"
echo "- Font sizing consistency"
echo "- Line height and paragraph spacing"
echo "- Text contrast and accessibility"
echo "- Heading hierarchy preservation"
echo ""

echo "Phase 7: Color and Visual Design"
echo "Analyze visual design across all sections and devices:"
echo "- Color scheme consistency"
echo "- Brand color usage"
echo "- Background and text color contrast"
echo "- Visual element styling"
echo ""

echo "=== Key Issues to Focus On (Based on Automated Analysis) ==="
echo "1. Pricing section missing on tablet and mobile devices"
echo "2. Footer section not detected on any device"
echo "3. Potential navigation overflow on mobile devices"
echo "4. Layout compression on smaller screens"
echo ""

echo "=== Report Deliverables ==="
echo "Create a comprehensive report with:"
echo "1. Executive Summary"
echo "2. Methodology"
echo "3. Section-by-Section Analysis"
echo "4. Cross-Device Comparison Findings"
echo "5. Typography and Visual Design Assessment"
echo "6. Issue Catalog with Prioritization"
echo "7. Technical Recommendations"
echo "8. Conclusion"
echo ""

echo "=== Reference Materials ==="
echo "See also:"
echo "- /root/projects/ai-automation-ru-final/IMAGE_ANALYSIS_INSTRUCTIONS_SECTION_BASED.md"
echo "- /root/projects/ai-automation-ru-final/RESPONSIVE_DESIGN_ANALYSIS.md"
echo "- /root/projects/ai-automation-ru-final/RESPONSIVE_SCREENSHOTS_SUMMARY.md"
echo ""
echo "=== Completion ==="
echo "Save your final analysis report as:"
echo "/root/projects/ai-automation-ru-final/DETAILED_VISUAL_ANALYSIS_REPORT_SECTION_BASED.md"